### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by neutrinonerd3333** [NERSC/slurm-magic#5]
Possibly a dumb question, but I can't find any installation instructions for this. Is it possible / can it be made possible to install this with `pip` or `conda`?

**Comment by rcthomas** [comment]
Have you tried e.g.

    pip install --no-cache-dir git+https://github.com/NERSC/slurm-magic.git

?  PRs fixing the docs or build system are welcome.

**Comment by neutrinonerd3333** [comment]
I was able to install `slurm-magic` into a conda environment by including the following in an `environment.yml` file. I'd be happy to start a small "Installation" section in the readme in a PR.

```yaml
  - pip:
    - git+https://github.com/NERSC/slurm-magic.git
```

**Comment by neutrinonerd3333** [comment]
I just made [a quick PR](https://github.com/NERSC/slurm-magic/pull/6) with some documentation updates, closing this issue!
